import { type Models } from 'appwrite';

/**
 * This file is auto-generated by the Appwrite CLI. 
 * You can regenerate it by running `appwrite types -l ts /home/nathfavour/Documents/code/bainaryglobe/bainaryglobe.com`.
 */

export enum Role {
  ADMINPRIVILEGEDREGULARPRODUCT_OWNERTHIRD_PARTY = "admin,privileged,regular,product_owner,third_party"
}

export enum Type {
  BLOGDASHBOARDANALYTICS = "blog,dashboard,analytics"
}

export enum AccessLevel {
  READWRITEADMIN = "read,write,admin"
}

export enum Type {
  PAGEBLOGFOOTER = "page,blog,footer"
}

export type Users = Models.Document & {
  userId: string;
  email: string;
  name: string;
  role: Role;
  products: string[] | null;
  oauthProviders: string[] | null;
  createdAt: string;
  updatedAt: string | null;
}

export type Products = Models.Document & {
  productId: string;
  name: string;
  description: string | null;
  standalone: boolean;
  ourApp: boolean;
  owners: string[] | null;
  modules: string[] | null;
  oauthEnabled: boolean;
  createdAt: string;
  updatedAt: string | null;
}

export type Modules = Models.Document & {
  moduleId: string;
  productId: string;
  name: string;
  type: Type;
  config: string | null;
  createdAt: string;
  updatedAt: string | null;
}

export type Permissions = Models.Document & {
  permissionId: string;
  userId: string;
  productId: string;
  moduleId: string | null;
  accessLevel: AccessLevel;
  createdAt: string;
  updatedAt: string | null;
}

export type OAuthClients = Models.Document & {
  clientId: string;
  name: string;
  redirectUris: string[];
  ourApp: boolean;
  ownerId: string;
  scopes: string[] | null;
  verificationSkipped: boolean | null;
  createdAt: string;
  updatedAt: string | null;
}

export type Content = Models.Document & {
  contentId: string;
  productId: string;
  moduleId: string;
  data: string;
  createdBy: string;
  createdAt: string;
  updatedAt: string | null;
  type: Type;
}

